Base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('order/', include('order.urls', namespace='order')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

order/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
    path('myorders/', views.MyOrdersView.as_view(), name='myorder'),
    path('delete/<int:order_id>/', views.DelOrder.as_view(), name='delorder'),
    # path('pay/', views.PayOrder.as_view(), name='payorder')

]

order/models.py
from django.db import models
from home.models import ProductModel
from accounts.models import UserModel


class OrderModel(models.Model):
    """ a model for saving open orders( orders that are just in cart) """
    pro_order = models.ForeignKey(ProductModel, on_delete=models.CASCADE, related_name="order_pro")
    order_size = models.CharField(max_length=50, blank=True, null=True)
    user_order = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name="order_user")


class Paymodel(models.Model):
    """when a client pay money for buy product"""
    pro_orders = models.ForeignKey(ProductModel, on_delete=models.CASCADE, related_name="order_proo")
    order_sizes = models.CharField(max_length=50, blank=True, null=True)
    user_orders = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name="order_userr")

order/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import OrderModel, Paymodel
from home.models import ProductModel
from django.contrib import messages
from accounts.models import UserModel


class MyOrdersView(View):
    """ because of this class customer can see all products
                              that already add to cart and can delete them """

    def get(self, request):
        if request.user.is_authenticated:
            user_orders = OrderModel.objects.filter(user_order=request.user).values()
            all_pay = 0
            pro = []
            for x in user_orders:
                s = ProductModel.objects.get(pk=x['pro_order_id'])
                r = s.pro_price
                all_pay += int(r)
                pro.append(ProductModel.objects.get(pk=x["pro_order_id"]))
            proder = zip(pro, user_orders)
            user_paid = Paymodel.objects.filter(user_orders=request.user).values()
            return render(request, "order/myorders.html", {"proder": proder, "all_pay": all_pay, "paid_pro": user_paid})
        else:
            messages.info(request, "you have to register in site first")
            return redirect("accounts:register")

    def post(self, request):
        user_orders = OrderModel.objects.filter(user_order=request.user).values()
        user_orm = OrderModel.objects.filter(user_order=request.user)
        # print(user_orders[0])
        for x in user_orders:
            user = UserModel.objects.get(id=x['user_order_id'])
            pro = ProductModel.objects.get(id=x['pro_order_id'])
            new_record = Paymodel(pro_orders=pro, order_sizes=x['order_size'], user_orders=user)
            new_record.save()
        for y in user_orm:
            y.delete()
        return redirect("order:myorder")


class DelOrder(View):
    """ a class for handling delete orders"""

    def get(self, request, order_id):
        pro = OrderModel.objects.get(id=order_id)
        pro.delete()
        messages.info(request, "product removed from your Cart")
        return redirect('order:myorder')

order/templates/order/myorders.html
{% extends 'base.html' %}
{% block body %}
{% if proder %}
{% for p,o in proder %}
<div class="card" style="width: 18rem;margin:20px;display:inline-block;" xmlns:order="http://www.w3.org/1999/xhtml">
  <img src="{{p.pro_image.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{p.pro_name}}</h5>
    <p class="card-text">{{p.pro_price}}$</p>
    <p class="card-text">{{o.order_size}}</p>

    <a href="{% url 'order:delorder' o.id %}"class="btn btn-danger"> Delete</a>
  </div>
</div>
{% endfor %}
<div style="background-color:green;text-align:right;padding:20px;">
  <form action="" method="post">
    {% csrf_token %}
    <button class="btn btn-success" style="padding:10px;margin-right:20px;">Buy</button>
  </form>
<a href="#" class="btn btn-primary" style="padding:10px;margin-right:20px;">Cost of all products : {{all_pay}}$</a>
</div>
{% else %}
<p style="text-align:center"> your order cart is empty </p>
{% endif %}


<br>
<hr>
<br>
<h3>products that you paid and are in way to you</h3>
{% if paid_pro%}
{% for x in paid_pro %}
<div class="card" style="width: 18rem;margin:20px;display:inline-block;" xmlns:order="http://www.w3.org/1999/xhtml">
  <div class="card-body">
    <h5 class="card-title">{{x.pro_orders}}</h5>
    <p class="card-text">{{x.order_sizes}}$</p>
  </div>
</div>
{% endfor %}
{% endif%}
{% endblock %}