Base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('order/', include('order.urls', namespace='order')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('login/', views.UserLoginView.as_view(), name='login')
]

home/urls.py
from django.urls import path
from home import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='homepage'),
    path('category/<slug:cat_slug_url>/',
         views.CategoryView.as_view(), name='categorypage'),
    path('products/<int:pro_id>/<slug:pro_slug_url>/', views.ProductView.as_view(), name='productpage')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
    path('myorders/', views.MyOrdersView.as_view(), name='myorder'),
    path('delete/<int:order_id>/', views.DelOrder.as_view(), name='delorder'),
    # path('pay/', views.PayOrder.as_view(), name='payorder')

]

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-success">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Test Website</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:homepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>

          <!-- shoes part -->

          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/category/shoes">Shoes</a></li>
            <ul>
              <li><a class="dropdown-item" href="/category/men_shoes">men's Shoes</a></li>
              <ul><li><a class="dropdown-item" href="/category/men_sport_shoes">sport shoes</a></li>
                  <li><a class="dropdown-item" href="/category/men_formal_shoes">formal shoes</a></li>
              </ul>

              <li><a class="dropdown-item" href="/category/women_shoes">Women's Shoes</a></li>
              <ul>
                <li><a class="dropdown-item" href="/category/women_sport_shoes">sport shoes</a></li>
                <li><a class="dropdown-item" href="/category/women_formal_shoes">formal shoes</a></li>
              </ul>
              <li><a class="dropdown-item" href="/category/children_shoes">Children's shoes</a></li>
            </ul>


            <li class="dropdown-divider"></li>

            <!-- dress part -->



            <li><a class="dropdown-item" href="/category/clothes">Clothes</a></li>
            <ul>
              <li><a class="dropdown-item" href="/category/men_clothes">Men's clothes</a></li>
              <li><a class="dropdown-item" href="/category/men_pants">Men's pants</a></li>
              <li><a class="dropdown-item" href="/category/women_clothes">Women's clothes</a></li>
              <li><a class="dropdown-item" href="/category/women_pants">Women's pants</a></li>
            </ul>


            <!-- watch part -->
            <li class="dropdown-divider"></li>


            <li><a class="dropdown-item" href="/watches/">Watches</a></li>
            <ul>
              <li><a class="dropdown-item" href="/category/men_watches">men's watch</a></li>
              <li><a class="dropdown-item" href="/category/women_watches">women's watch</a></li>
            </ul>

            <!-- backpack part -->
            <li class="dropdown-divider"></li>


            <li><a class="dropdown-item" href="/backpacks">Backpacks</a></li>

          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'order:myorder' %}">Your cart</a>
        </li>
        {%if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">logout</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-info" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% if messages %}
  {% for msg in messages %}
<div class="alert alert-{{msg.tags}}" role="alert">
{{msg}}
</div>
{% endfor %}
{% endif %}